### ISSUE TITLE
--no-pin doesn't work

### ISSUE THREAD

**Issue by AndreaPi** [ivanlen/pipreqsnb#18]
```
$ pipreqsnb --no-pin .
pipreqs  .
INFO: Successfully saved requirements file in ./requirements.txt
```

It looks like `pipreqsnb` is not passing `pipreqs` the `--no-pin` option, but only the folder path `.`. As a matter of fact, the resulting `requirements.txt` does pin versions:

```
$ cat requirements.txt 
pandas==1.2.4
matplotlib==3.4.2
numpy==1.20.3
```

Can you fix? Thanks. I'm using `pipreqsnb  0.2.3` System info:

```

$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by ivanlen** [comment]
Hi @AndreaPi, sorry for the late reply. I've been quite busy with some projects. In these days I will be working in this.
Cheers.

**Comment by AndreaPi** [comment]
Any news on this?

**Comment by NHanser** [comment]
I found a way to fix it.
In fact it's due to ArgumentsParser that modify arguments converting dash to underscore character. When generating arguments for pipreqs, it is needed to convert back underscore to dash character
I modified following function :
`def generate_pipreqs_str(args):
    pipreqs_str = ''
    for arg, val in args.__dict__.items():
        if arg.replace('_','-') in pipreqs_options_store and val:
            pipreqs_str += ' --{}'.format(arg.replace('_','-'))
        elif arg.replace('_','-') in pipreqs_options_args and val is not None:
            pipreqs_str += ' --{} {}'.format(arg.replace('_','-'), val)
    pipreqs_str += ' {}'.format(args.path)
    return pipreqs_str`

**Comment by ivanlen** [comment]
Hey @NHanser , thanks for the PR. I've been quite busy lately.
I already merged your PR.
@AndreaPi  could you please upload to latest version and see if your issue is solved?
`pip install pipreqsnb==0.2.4`

Thank you both
Cheers

**Comment by ivanlen** [comment]
I close the issue because there is not activity and also I think that is fixed. 
Please if you still encounter this problem reopen it.

**Comment by johannesgreiner** [comment]
hi I just came across this issue using version 0.2.4. I'm using pipreqsnb inside a conda environment on Win 10. 
`pipreqs  --use-local --force .` and other options work, but as soon as I include `--no-pin` I get a usage message as the only output
> Usage:
    pipreqs [options] [<path>]
  
  @NHanser @ivanlen let's see

**Comment by johannesgreiner** [comment]
oh I see, there might have been a breaking change in `pipreqs`. it's now using the option `--mode no-pin` rather than `--no-pin`.
that's in pipreqs version: 0.4.11
