### ISSUE TITLE
--ignore  does not work

### ISSUE THREAD

**Issue by jpyrett** [ivanlen/pipreqsnb#4]
I am seeing all kinds of problems with this.  Must have the ignore dir ending in '/' or it does not work. Line 53:  when it reads in the file, the path of:  .  is not working.  There is just something fatal with this.  Recursive = True is a bad choice.  We should be able to select the notebook to analyze , not every .ipynb at once.   It is totally broken

**Comment by ivanlen** [comment]
Hi @jpyrett , thank you for the feedback.
What functionality are you looking for? Analyse one single ipynb instead of a whole folder of files?

**Comment by ivanlen** [comment]
Hi @jpyrett, would you mind reading [this PR](https://github.com/ivanlen/pipreqsnb/pull/7) which I think that will solve the bad behaviour  that you mention.

Cheers,

**Comment by ivanlen** [comment]
Hi @jpyrett I close the issue for the moment. I think that #7 solves the issue.
Please do not hesitate to open a new issue if you find any undesired behaviour.
