### ISSUE TITLE
Export the requirements for a single notebook

### ISSUE THREAD

**Issue by OdysseeT** [ivanlen/pipreqsnb#9]
Hi there!
Sometime I have multiple notebooks that are not related to each other, or for used different tasks.
It could be nice if I could run pipreqsnb for a single notebook, e.g.:
pipreqsnb -nb mynb.ipynb

Thanks a lot!

**Comment by ivanlen** [comment]
Hey @OdysseeT , thank you for your feedback.
I followed your suggestion and I addressed feature in PR #10 .

Please update `pipreqsnb` to the latest version, currently 0.2.1.
Feel free tu suggest any other improvement, comment, bug or suggestion.

Cheers!
